config/routes.rb
Rails.application.routes.draw do


  get '/', to: "welcome#index", as: :home
  resources :questions do
    resources :answers
  end
  resources :users
  resource :session, only: [:new, :create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, :to => :crud

    can :crud, Question do |question|
      question.user == user
    end

    can :crud, Answer do |answer|
      answer.user == user
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :title, presence: true, uniqueness: true, length: { in: 5..20 }
  validates :content, presence: true, length: { in: 5..500 }
  validates :view_count, numericality: { greater_than_or_equal_to: 0 }

  before_save :squeeze
  before_validation :set_view_count

  private

  def squeeze
    self.title.squeeze!(' ')
  end

  def set_view_count
    self.view_count ||= 0
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :nullify
  has_many :answers, dependent: :nullify

  validates :name,  presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  before_save { self.email = email.downcase }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, :find_question
  before_action :find_answer, :authorize_user!, only: [:destroy]

  def create
    @answer = Answer.new answer_params
    @answer.question = @question
    @answer.user = current_user
    if @answer.save
      redirect_to @question
    else
      @answers = @question.answers.order(created_at: :desc)
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    redirect_to @question
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find params[:question_id]
  end

  def find_answer
    @answer = Answer.find params[:id]
  end

  def authorize_user!
    unless can?(:crud, @answer)
      flash[:danger] = 'Access Denied!'
      redirect_to home_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_session_path
      flash[:danger] = 'You must sign in or sign up first!'
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      flash[:success] = 'Thank you for creating a question.'
      redirect_to @question
    else
      render :new
    end

  end

  def show
    @question.update(view_count: @question.view_count + 1)
    @answers = @question.answers.order(created_at: :desc)
    @answer = Answer.new
  end

  def index
    @questions = Question.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @question.update question_params
      flash[:success] = 'Your question has been updated.'
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = 'Your question has been deleted.'
      redirect_to questions_path
    else
      flash.now[:danger] = 'Delete failed.'
      render @question
    end

  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def find_question
    @question = Question.find params[:id]
  end

  def authorize_user!
    unless can?(:crud, @question)
      flash[:danger] = 'Access Denied!'
      redirect_to home_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back! #{current_user.name}"
      redirect_to home_path
    else
      flash.now[:warning] = 'Wrong email or password!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Sign Out.'
    redirect_to home_path
  end


private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Thank you for signing up!'
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[:success] = 'Update completed.'
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def find_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'MiniAnswers'
    if page_title.empty?
       base_title
     else
       page_title + " | " + base_title
     end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <%= link_to 'MiniAnswers', home_path, class: 'navbar-brand ml-4' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto mr-5">
      <%= link_to 'New Question', new_question_path,
          class: 'nav-item nav-link' %>
      <%= link_to 'Question List', questions_path,
          class: 'nav-item nav-link' %>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
          <%= link_to 'Settings', edit_user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Log Out', session_path,
          method: :delete, data: { confirm: "Log Out?" },
          class: 'dropdown-item' %>
        </div>
      </li>

      <% else %>
        <%= link_to 'Sign Up', new_user_path,
        class: 'nav-item nav-link' %>
        <%= link_to 'Log In', new_session_path,
        class: 'nav-item nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid" id="mainContainer">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<div class="container mt-4">
  <%= form_for @question do |f| %>
    <%= render 'shared/error_messages', target: @question %>

    <div class="form-group">
      <%= f.label 'title' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label 'content' %>
      <%= f.text_area :content, rows: 5, class: 'form-control' %>
    </div>

    <%= submit_tag "#{@question.new_record? ? 'Create' : 'Update'} Question", class: 'btn btn-secondary btn-sm questionBtn' %>

  <% end %>

</div>

app/views/questions/edit.html.erb
<div class="container questionContainer">
  <div id="questionForm">
    <%= render 'form' %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container questionIndexContainer">
  <div id="questionIndex">
    <% @questions.each do |question| %>
      <p>✸ <%= link_to question.title, question, class: "question-index-item" %></p>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container questionContainer">
  <div id="questionForm">
    <%= render 'form' %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container" id="questionShowContainer">
  <div id="questionShowCard">
    <h3>
      <%= @question.title %>
      <span class="viewCount"><small>view: <%= @question.view_count %></small></span>
    </h3>
    <p class="content"><%= @question.content %></p>

    <div class="dateInfo">
      <span class="badge badge-success">Created: <%= @question.created_at.strftime('%d %b %Y %l:%M %p') %></span>
      <span class="badge badge-info">Updated: <%= @question.updated_at.strftime('%d %b %Y %l:%M %p') %></span>
    </div>

    <% if can?(:crud, @question) %>
      <%= link_to 'edit',
          edit_question_path(@question),
          class: 'btn btn-info btn-sm' %>
      <%= link_to 'delete', @question,
          method: :delete,
          data: {confirm: 'Delete this question?'},
          class: 'btn btn-danger btn-sm ml-2' %>
    <% end %>
  </div>

  <div id="answerForm" class="mt-3">
    <%= form_for [@question, @answer] do |f| %>
      <%= render 'shared/error_messages', target: @answer %>

    <div class="form-group">
      <%= f.label 'give an answer', class: 'answerFormLabel' %>
      <%= f.text_area :body, rows: 5, class: 'form-control' %>
    </div>

    <%= f.submit 'submit', class: 'btn btn-secondary btn-sm questionBtn' %>
    <% end %>
  </div>

  <div id="answerShowCard" class="mt-3">
    <h5>Answers:</h5>
    <% @answers.each do |answer| %>
      <div class="answerBlock">
        <p> <%= answer.body %> </p>
        <p> <small>created at: <%= answer.created_at.strftime('%d %b %Y %l:%M %p') %> </small> </p>

        <% if can?(:crud, answer) %>
          <%= link_to 'delete',
              question_answer_path(@question,answer),
              method: :delete,
              class: 'btn btn-sm btn-danger'
          %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="errorsBox">
    <h5>Oops.This form has <strong><%= pluralize(target.errors.count, "error") %></strong>.</h5>
    <ul>
      <% target.errors.full_messages.each do |m| %>
      <li>
        <%= m %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="userEditForm">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', target: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary mt-2" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'sign up') %>
<div class="signUpFormContainer">
  <div class="row">
    <div class="col-md-6 col-md-offset-3" id="signUpForm">

      <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', target: @user %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'  %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control'  %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <%= f.submit "Sign up", class: "btn btn-primary btn-sm mt-2 signUpBtn" %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row userShowContainer">
  <div class="col-md-8">
    <section class="user_info">
      <h3><%= @user.name %></h3>
      <h5> <%= @user.email %> </h5>
      <p class="mt-5"><small><b>Signed up at:</b> <%= @user.created_at.strftime('%e %b %Y %H:%M %p') %></small> <small class="ml-3"><b>Updated at:</b> <%= @user.updated_at.strftime('%e %b %Y %H:%M %p') %></small></p>
    </section>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="homeContainer">
  <div class="container">
    <h1 class="display-4">Mini Answers</h1>
    <p class="lead">
      This is an app for users to ask questions and provide answers.
    </p>
    <% if user_signed_in? %>

    <% else %>
      <%= link_to "Sign up now", new_user_path, class: "btn btn-light" %>
    <% end %>
  </div>
</div>